name: 自動更新CB價格

# 每天台股收盤後執行
on:
  schedule:
    # 每天下午2點(台北時間)執行 (UTC+8)
    - cron: '0 6 * * 1-5'  # 週一到週五，UTC 6:00 = 台北 14:00
  
  # 也可以手動觸發
  workflow_dispatch:

jobs:
  update-cb-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install requests pandas beautifulsoup4 lxml
      
      - name: Fetch CB prices
        run: |
          python3 scripts/fetch_cb_prices.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/prices/
          git diff --quiet && git diff --staged --quiet || (git commit -m "自動更新CB價格 $(date +'%Y-%m-%d %H:%M')" && git push)
